{
    "Entities": "Entities",
    "New Entity": "New Entity",
    "Policies": "Policies",
    "New Policy": "New Policy",
    "View Policies": "View Policies",
    "Help Area": "Help Area",
    "Bank Accounts": "Bank Accounts",
    "Help Phones": "Help Phones",
    "ViewPolicy.New Receipt": "New Receipt",
    "Renewal": "Renewal",
    "Cancellation": "Cancellation",
    "Endorsement": "Endorsement",
    "Holder": "Holder",
    "Application":"Application No",
    "Agency":"Select Agency",
    "Producer":"Producer",
    "Package":"Policy Group",
    "Provider":"Ins. Provider",
    "SLOB":"SLOB",
    "Finance":"Finance",
    "MOP":"Means of Payment",
    "StartDate":"Start Date",
    "Frequency":"Frequency",
    "InitialStart":"Initial Start Date",
    "EndDate":"End Date",
    "QuoteID":"QuoteID",
    "FromTransfer":"From Transfer",
    "SpecialCommission":"Special Commission",
    "AgreedPremium":"Agreed Premium",
    "Currency":"Currency",
    "New":"New",
    "Add":"Add",
    "ObjectAmount":"Object Amount",
    "SignAbove":"SignAbove",
    "Clear":"Clear",
    "EntityKind":"Entity Kind",
    "ReferencedBy":"Referenced By",
    "LegalForm":"Legal Form",
    "DOB":"Date of Birth",
    "VAT":"V.A.T.",
    "TaxOffice":"Tax Office",
    "ProducerClientBelongTo":"Select the producer that the client belongs to",
    "LastName":"Last Name",
    "FirstName":"First Name",
    "MiddleName":"Middle Name",
    "BirthName":"Birth Name",
    "Gender":"Gender",
    "CompanyName":"Company Name",
    "CompanyLegalName":"Company Legal Name",
    "Nationality":"Nationality",
    "AMKA":"Social Security #",
    "Identity":"Identity or Passport",
    "Relations": "Add relationships with existing entities",
    "ContactType": "Select Contact Type",
    "Floor": "Floor",
    "DoorBell": "Door Bell",
    "POBox": "P.O. Box",
    "AdditionalInstructions": "Additional Instructions",
    "Street": "Street",
    "StreetNumber": "Street Number",
    "PostalCode": "Postal Code",
    "Area": "Area",
    "City": "City",
    "CountryCode": "Country Code",
    "Country": "Country",
           
    "Projects": "Projects",
    "Msgs": "Msgs",
    "Notify": "Notify",
    "Tasks": "Tasks",
    "Recent projects": "Recent projects",
    "Find reports and more": "Find reports and more",
    "john.doe": "john.doe",
    "Dashboard": "Dashboard",
    "Angular Stuff": "Angular Stuff",
    "UI Bootstrap": "UI Bootstrap",
    "Get Locale JSON": "Get Locale JSON",
    "Inbox": "Inbox",
    "Graphs": "Graphs",
    "Flot Chart": "Flot Chart",
    "Morris Charts": "Morris Charts",
    "Inline Charts": "Inline Charts",
    "Dygraphs": "Dygraphs",
    "Tables": "Tables",
    "Normal Tables": "Normal Tables",
    "Data Tables": "Data Tables",
    "Forms": "Forms",
    "Smart Form Elements": "Smart Form Elements",
    "Smart Form Layouts": "Smart Form Layouts",
    "Smart Form Validation": "Smart Form Validation",
    "Bootstrap Form Elements": "Bootstrap Form Elements",
    "Form Plugins": "Form Plugins",
    "Wizards": "Wizards",
    "Bootstrap Editors": "Bootstrap Editors",
    "Dropzone": "Dropzone",
    "UI Elements": "UI Elements",
    "General Elements": "General Elements",
    "Buttons": "Buttons",
    "Icons": "Icons",
    "Font Awesome": "Font Awesome",
    "Glyph Icons": "Glyph Icons",
    "Grid": "Grid",
    "Tree View": "Tree View",
    "Nestable Lists": "Nestable Lists",
    "JQuery UI": "JQuery UI",
    "Typography": "Typography",
    "Six Level Menu": "Six Level Menu",
    "Item #2": "Item #2",
    "Sub # 2.1": "Sub # 2.1",
    "Item #2.1.1": "Item #2.1.1",
    "Expand": "Expand",
    "File": "File",
    "Delete": "Delete",
    "Item #3": "Item #3",
    "3rd Level": "3rd Level",
    "Calendar": "Calendar",
    "Widgets": "Widgets",
    "Gallery": "Gallery",
    "GMap Skins": "GMap Skins",
    "Miscellaneous": "Miscellaneous",
    "Other Pages": "Other Pages",
    "Forum Layout": "Forum Layout",
    "Profile": "Profile",
    "Timeline": "Timeline",
    "Pricing Tables": "Pricing Tables",
    "Invoice": "Invoice",
    "Login": "Login",
    "Register": "Register",
    "Locked Screen": "Locked Screen",
    "Error 404": "Error 404",
    "Error 500": "Error 500",
    "Blank Page": "Blank Page",
    "Email Template": "Email Template",
    "Search Page": "Search Page",
    "CK Editor": "CK Editor",
    "SmartAdmin Intel": "SmartAdmin Intel",
    "Different Versions": "Different Versions",
    "Documentation": "Documentation",
    "Bug Tracker": "Bug Tracker",
    "Home": "Home",
    "Mail 14": "Mail 14",
    "Maps": "Maps",
    "My Profile": "My Profile",
    "Page Header": "Page Header",
    "Subtitle": "Subtitle"
}