{
    "Entities": "Οντότητες",
    "New Entity": "Νέα Οντότητα",
    "Policies": "Συμβόλαια",
    "New Policy": "Νέο Συμβόλαιο",
    "View Policies": "Συμβόλαια Πελατών",
    "Help Area": "Βοήθεια",
    "Bank Accounts": "Τραπεζικοί Λογαριασμοί",
    "Help Phones": "Χρήσιμα Τηλέφωνα",
    "ViewPolicy.New Receipt": "Δημιουργία απόδειξης",
    "Renewal": "Ανανέωση",
    "Cancellation": "Ακύρωση",
    "Endorsement": "Πρόσθετη Πράξη",
    "Holder": "Λήπτης",
    "Application":"Αρ. Αϊτησης",
    "Agency":"Εταιρία που ανήκει:",
    "Producer":"Συνεργάτης",
    "Package":"Πακέτο Συμβ.",
    "Provider":"Ασφ.Εταιρία",
    "SLOB":"Υποκλάδος",
    "Finance":"Λογ.Κωδ.",
    "MOP":"Τρόπος Πληρ.",
    "StartDate":"Ημ. έναρξης",
    "Frequency":"Συχνότητα πλ.",
    "InitialStart":"Αρχική Ημ.Έναρξης",
    "EndDate":"Ημ. Λήξης",
    "QuoteID":"Αρ. Προσφοράς",
    "FromTransfer":"Από μεταφορά",
    "SpecialCommission":"Ειδική προμ.",
    "AgreedPremium":"Συμφωνημένη Δόση",
    "Currency":"Νόμισμα",
    "New":"Δημιουργία",
    "Add":"Προσθήκη",
    "ObjectAmount":"Αξία Αντικειμένου",
    "SignAbove":"Υπογράψτε επάνω",
    "Clear":"Καθαρισμός",
    "EntityKind":"Είδος Οντότητας",
    "ReferencedBy":"Σύσταση από:",
    "LegalForm":"Νομική μορφή",
    "DOB":"Ημ. Γέννησης",
    "VAT":"Α.Φ.Μ.",
    "TaxOffice":"Δ.Ο.Υ.",
    "ProducerClientBelongTo":"Επιλέξτε τον συνεργάτη στον οποίο ανήκει η οντότητα",
    "LastName":"Επίθετο",
    "FirstName":"Όνομα",
    "MiddleName":"Πατρώνυμο",
    "BirthName":"Βαφτιστικό",
    "Gender":"Φύλλο",
    "CompanyName":"Διακριτικός τίτλος Εταιρίας",
    "CompanyLegalName":"Επίσημη επωνυμία εταιρίας",
    "Nationality":"Εθνικότητα",
    "AMKA":"Α.Μ.Κ.Α.",
    "Identity":"Α.Δ.Τ. ή Διαβατήριο",
    "Relations": "Προσθέστε σχέσεις με υπάρχουσες οντότητες",
    "ContactType": "Είδος επικοινωνίας",
    "Floor": "Όροφος",
    "DoorBell": "Κουδούνι",
    "POBox": "Ταχ. Θυρίδα",
    "AdditionalInstructions": "Επιπλέον οδηγίες",
    "Street": "Δρόμος",
    "StreetNumber": "Αριθμός",
    "PostalCode": "Τ.Κ.",
    "Area": "Περιοχή",
    "City": "Πόλη",
    "CountryCode": "Κωδ. Χώρας",
    "Country": "Χώρα",



    "Projects": "Projects",
    "Msgs": "Msgs",
    "Notify": "Notify",
    "Tasks": "Tasks",
    "Recent projects": "Recent projects",
    "Find reports and more": "Find reports and more",
    "john.doe": "john.doe",
    "Dashboard": "Κεντρική Σελίδα",
    "Angular Stuff": "Angular Stuff",
    "UI Bootstrap": "UI Bootstrap",
    "Get Locale JSON": "Get Locale JSON",
    "Inbox": "Inbox",
    "Graphs": "Graphs",
    "Flot Chart": "Flot Chart",
    "Morris Charts": "Morris Charts",
    "Inline Charts": "Inline Charts",
    "Dygraphs": "Dygraphs",
    "Tables": "Tables",
    "Normal Tables": "Normal Tables",
    "Data Tables": "Data Tables",
    "Forms": "Forms",
    "Smart Form Elements": "Smart Form Elements",
    "Smart Form Layouts": "Smart Form Layouts",
    "Smart Form Validation": "Smart Form Validation",
    "Bootstrap Form Elements": "Bootstrap Form Elements",
    "Form Plugins": "Form Plugins",
    "Wizards": "Wizards",
    "Bootstrap Editors": "Bootstrap Editors",
    "Dropzone": "Dropzone",
    "UI Elements": "UI Elements",
    "General Elements": "General Elements",
    "Buttons": "Buttons",
    "Icons": "Icons",
    "Font Awesome": "Font Awesome",
    "Glyph Icons": "Glyph Icons",
    "Grid": "Grid",
    "Tree View": "Tree View",
    "Nestable Lists": "Nestable Lists",
    "JQuery UI": "JQuery UI",
    "Typography": "Typography",
    "Six Level Menu": "Six Level Menu",
    "Item #2": "Item #2",
    "Sub # 2.1": "Sub # 2.1",
    "Item #2.1.1": "Item #2.1.1",
    "Expand": "Expand",
    "File": "File",
    "Delete": "Delete",
    "Item #3": "Item #3",
    "3rd Level": "3rd Level",
    "Calendar": "Calendar",
    "Widgets": "Widgets",
    "Gallery": "Gallery",
    "GMap Skins": "GMap Skins",
    "Miscellaneous": "Miscellaneous",
    "Other Pages": "Other Pages",
    "Forum Layout": "Forum Layout",
    "Profile": "Profile",
    "Timeline": "Timeline",
    "Pricing Tables": "Pricing Tables",
    "Invoice": "Invoice",
    "Login": "Login",
    "Register": "Register",
    "Locked Screen": "Locked Screen",
    "Error 404": "Error 404",
    "Error 500": "Error 500",
    "Blank Page": "Blank Page",
    "Email Template": "Email Template",
    "Search Page": "Search Page",
    "CK Editor": "CK Editor",
    "SmartAdmin Intel": "SmartAdmin Intel",
    "Different Versions": "Different Versions",
    "Documentation": "Documentation",
    "Bug Tracker": "Bug Tracker",
    "Home": "Home",
    "Mail 14": "Mail 14",
    "Maps": "Maps",
    "My Profile": "My Profile",
    "Page Header": "Page Header",
    "Subtitle": "Subtitle"
}